# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Junction' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Junction
	pod "Pulsator"
pod 'LTHRadioButton'
  target 'JunctionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JunctionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
